### ISSUE TITLE
Back - Workflow d'inscription

### ISSUE THREAD

**Issue by sopalin** [Societes-AnitCOR/societiesanticor.org#11]
Il est possible de s'inspirer du workflow d'inscription qui avait déjà été utilise sur la version précédente du site : http://cursbcj.cluster028.hosting.ovh.net/. Pour accéder au formulaire d'inscription, il suffit de cliquer sur le bouton "Je veux aider" visible sur la landing page.

Contrairement a l'installation precedente, dans la base de donnees actuelle, les tables users et company sont independantes. Donc pour pouvoir reprendre le code precedent, il faut l'adapter a la nouvelle configuration.

- [x] 1. Formulaire d'inscription quand le user clique sur le boutton "Je veux participer"
- [x] 2. Apres inscription le user est redirige vers une page Espace Entreprise 
![image](https://user-images.githubusercontent.com/5632649/82151301-34975400-985b-11ea-8cb1-96c09336b6ad.png)
- [ ] 3. Il peut alors completer ses informations en cliquant sur un bouton "mettre a jour mes informations"
- [ ] 4. Dans ce cas, il est redirige vers un formulaire pour completer ses infos.
![image](https://user-images.githubusercontent.com/5632649/82151345-66a8b600-985b-11ea-8e50-e694e1c67749.png)

**Comment by eznix86** [comment]
le back d'inscription est-il géré par le easy-admin ?

**Comment by eznix86** [comment]
@joshbradfield @p3ters0ft

**Comment by joshbradfield** [comment]
@theArtechnology , pour l'instant je ne crois pas

**Comment by p3ters0ft** [comment]
Désolé je ne comprend pas trop bien ta question @theArtechnology.

Si le formulaire d'inscription (client) est déjà OK. Le code serveur, je peux m'en occuper. Mais Easy Admin ne gère pas pour l'instant les scripts front-office

**Comment by sopalin** [comment]
Est ce qu'on peut finalement simplifier le workflow d'inscription et de connexion avec 1 user / 1 entreprise ? Je propose le workflow suivant. 
1. Inscription en 2 étapes 
i) saisie des infos user
![image](https://user-images.githubusercontent.com/5632649/82815268-21a70400-9e99-11ea-8aad-750d229f8daf.png)
ii) saisie des infos essentielles company
![image](https://user-images.githubusercontent.com/5632649/82815130-cffe7980-9e98-11ea-9f98-b5127ecf1c00.png)
2.  Connexion
![image](https://user-images.githubusercontent.com/5632649/82815178-eefd0b80-9e98-11ea-8898-dc4e99850aa5.png)
