### ISSUE TITLE
Front - Landing page Ameliorations

### ISSUE THREAD

**Issue by sopalin** [Societes-AnitCOR/societiesanticor.org#19]
- [x] animer la page
     - [x] 3 images cliquables permettant d'acceder a 
          - [x]  1. une carte qui s'ouvre en fenêtre modale (voir l'issue sur "Integration carte")
          - [x]  2. la page annuaire pour rechercher une entreprise
          - [x]  3. la page videos des solutions face a la crise 
     - [x] le bouton "Je veux participer" renvoie a un formulaire d'inscription
     - [x] Dans le footer : 
         - [x] "Nous contacter" ouvre une page mail 
         - [x]  "FAQ" renvoie a la page FAQ (qui etait present sur la version precedente du site)
- [x] rendre le footer responsive
- [x] ameliorer l'aspect responsive du pargraphe "notre equipe" (pour l'instant ca reagit de facon responsive mais pas d'une facon qui soit harmonieuse)
- [x] cacher les menus deroulants "Type d'acteurs" et "Secteurs d'activites" dans la banniere pour la v1 mais il apparaitront dans la v2

**Comment by eznix86** [comment]
je prend ce issue

**Comment by kevingb21** [comment]
je reprends ce dev la
