### ISSUE TITLE
Annuaire - Trouver un moyen de diminuer le temps de chargement de la page

### ISSUE THREAD

**Issue by sopalin** [Societes-AnitCOR/societiesanticor.org#23]

**Comment by joshbradfield** [comment]
Le delai vu par @sopalin c'est peut-etre agravé par le server de debug de symfony

**Comment by eznix86** [comment]
c'est relier a quel issue ?

**Comment by joshbradfield** [comment]
@theArtechnology  Le server web de symfony est extrêmement lente sur windows, avec des délais de 4 seconds juste pour le page index. Je ne crois pas qu'on vas avoir cette issue sur le vrai site

**Comment by eznix86** [comment]
ah... oui ce n'est pas un soucis, on ferme ce issue la!
