### ISSUE TITLE
Integration-carte

### ISSUE THREAD

**Issue by sopalin** [Societes-AnitCOR/societiesanticor.org#5]
**A quoi ressemble cette carte ?**
http://umap.openstreetmap.fr/fr/map/entreprises-engages_446744?scaleControl=false&miniMap=true&scrollWheelZoom=false&zoomControl=true&allowEdit=true&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=true&datalayersControl=true&onLoadPanel=none&captionBar=false#6/47.040/2.109

**Comment est générée cette carte ?**

La carte reprend les données contenue dans une google spreadsheet 

la google spreadsheet :
https://docs.google.com/spreadsheets/d/1yCxNTeeG1py5qqTf2cHgZbk4njSPtzhc5XaTt3LB510/edit#gid=0

**Ou doit s'afficher cette carte ?**

La carte s'ouvre en fenêtre modale lorsque l'utilisateur clique sur la vignette représentant la carte sur la landing page.

![image](https://user-images.githubusercontent.com/5632649/81814513-2bd81280-9529-11ea-872b-ca762ea0098a.png)

**Comment by joshbradfield** [comment]
Au debut cette carte peut etre modifié a la main.

on peut integrer une iframe au debut:
```html
<iframe width="100%" height="600px" frameborder="0" allowfullscreen src="//umap.openstreetmap.fr/fr/map/entreprises-engages_446744?scaleControl=false&miniMap=true&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=false&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false#6/46.988/1.934"></iframe>
```

**Comment by joshbradfield** [comment]
A terme la carte doit etre generée depuis la base des données

**Comment by sopalin** [comment]
Et les entreprises seront directement ajoutées par les users qui s'inscrivent sur le site.

**Comment by kevingb21** [comment]
J'integre un iframe pour le moment
