### ISSUE TITLE
Integration-annuaire

### ISSUE THREAD

**Issue by sopalin** [Societes-AnitCOR/societiesanticor.org#6]
**A quoi ressemble l'annuaire ?**

![image](https://user-images.githubusercontent.com/5632649/81815051-d18b8180-9529-11ea-9514-ff01da21cd98.png)

**Comment cet annuaire est généré ?**
L'annuaire est generé depuis la liste des entreprises dans la base des donnes.

**Ou doit s'afficher cette page ?**

Sur la page Entreprises engagées qui est accessible depuis l'onglet du meme nom dans la navbar, ainsi que lorsque l'utilisateur clique sur la vignette : "Je recherche une entreprise engagée"

**Comment by sopalin** [comment]
A terme l'annuaire doit être généré depuis la base des données. Et les entreprises seront directement ajoutées par les users qui s'inscrivent sur le site.

**Comment by joshbradfield** [comment]
voir branch : dev/feat_companies_page
